<?php

namespace AppBundle\Repository;

/**
 * CopacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapacityRepository extends \Doctrine\ORM\EntityRepository
{
}
