<?php

namespace AppBundle\Repository;

/**
 * ProductionUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
