<?php

namespace AppBundle\Repository;

/**
 * TimeUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
